### ISSUE TITLE
Nova versão do Snack-WP

### ISSUE THREAD

**Issue by adriano** [snack/snack-wp#1]
Pessoal,

Vamos retomar o desenvolvimento do Snack-WP. O objetivo é criar um tema padrão para Wordpress que sirva de base para criação de sites institucionais e que melhore a qualidade final das nossas entregas. De certa forma ele já é assim atualmente, mas queremos evoluir.

Será inicialmente uma força-tarefa do time da A2ad, mas todos que seguem o projeto aqui no Github estão convidados para participar das discussões e colaborar.

A proposta inicial é dividir o trabalho em 3 grandes áreas: Framework, Front end / Visual e Plugins. Vamos tentar aproveitar o que existe de melhor em cada área.

Próximo passo: vou criar as [issues](https://github.com/snack/snack-wp/issues) com cada um dos itens abaixo e vamos discuti-los de forma isolada. 

**[Framework](https://github.com/snack/snack-wp/issues?q=is%3Aissue+is%3Aopen+label%3Aframework)**
- Estrutura de pastas e arquivos
- Gerenciador de dependências (Bower)
- Automatizador de tarefas (Gulp)
- Pré-processador de CSS (SASS)
- Guia de estilo do código (HTML, CSS e JS)
- Tema pai / tema filho

**[Front end / Visual](https://github.com/snack/snack-wp/issues?q=is%3Aissue+is%3Aopen+label%3A%22front+end+%2F+visual%22)**
- Grid
- Menus de navegação
- Tipografia
- Formulários
- Acessibilidade
- Gerador automático de guia de estilo

**[Plugins](https://github.com/snack/snack-wp/issues?q=is%3Aissue+is%3Aopen+label%3Aplugins)**
- SEO
- Cache
- Backup
- Formulários
- Google Analytics
- Facebook Pixel

[]s
Adriano.

**Comment by hussani** [comment]
Isso poderia começar separando o tema do componente de estilo.
Se a ideia é criar um tema que apenas utilize o Snack original, não existe motivo para duplicar os assets já publicados no outro pacote.

Se refere muito a issue https://github.com/snack/snack/issues/50.

Sobre plugins, a ideia é criar plugins compatíveis com o Snack ou fazer o Snack ser compatível com determinados plugins? Esta ideia pareceu um pouco vaga para mim.

**Comment by raphaelfabeni** [comment]
Eu concordo com o @hussani !  Acredito que o Snack tenha que se adaptar em qualquer lugar que for aplicado. Seja um WordPress ou não. Talvez algo pelo NPM também seria legal.

**Comment by adriano** [comment]
@hussani e @raphaelfabeni primeiro obrigado por participarem, eu sabia que podíamos contar com vocês.

> Se a ideia é criar um tema que apenas utilize o Snack original, não existe motivo para duplicar os assets já publicados no outro pacote.

Concordo, vamos tentar manter as coisas separadas, talvez no começo a gente tenha alguma dificuldade técnica para fazer isso.

> Sobre plugins, a ideia é criar plugins compatíveis com o Snack ou fazer o Snack ser compatível com determinados plugins? Esta ideia pareceu um pouco vaga para mim.

Lembram do [wp-plugins](https://github.com/a2ad/wp-plugins)? Inicialmente vamos listar os melhores plugins que utilizamos e depois vamos medir a performance e tentar incorporar alguns plugins para dentro do tema.

**Comment by raphaelfabeni** [comment]
Opa! :metal: 

Em relação ao primeiro item, eu ainda acredito na opção de ter um repositório único do Snack. Nem que na última solução, em um projeto em WP por exemplo, poderíamos clonar o Snack dentro da pasta de temas. Mas ainda assim existem algumas coisas que precisam ser pensadas como por exemplo:
- O Snack teria templates de páginas? Ou apenas os componentes Se tiver templates, existiram diferenças entre um template de lista de notícias (por exemplo) de um projeto em WP e um projeto usando outro CMS?

**Comment by adriano** [comment]
Um tema premium do WP do que eu imagino que poderia ser um dia o Snack-WP:
https://www.youtube.com/watch?v=QRVcsQm0I0c

Demo e módulos:
http://www.elegantthemes.com/preview/Divi/

**Comment by airton** [comment]
@hussani e @raphaelfabeni é isso mesmo, desde a primeira versão do Snack-WP a ideia é essa, o tema é uma cópia dos arquivos do Snack e adicionamos os arquivos php do tema, por isso do nome.

Só que esse processo hoje é manual, quando o Snack é atualizado agente copia os arquivos para o Snack-WP. 

Como agora nessa nova versão a ideia é ter um tema base pronto para ser usado, só instalar e começar a usar, não sei como ficaria esse clone do Snack para o Snack-WP que já teria o seu CSS próprio.

**Comment by guilima** [comment]
Seguindo o que o @airton comentou, iniciei diversas atualizações no snack-wp de modo a parte ao snack. Provavelmente o snack-wp ira se tornar uma mutação do snack, estando mais focado na otimização dos processos para criação de temas em wordpress.

**Comment by hussani** [comment]
Show de bola
