### ISSUE TITLE
Grid - Definir e implementar no tema

### ISSUE THREAD

**Issue by adriano** [snack/snack-wp#2]
Qual grid iremos utilizar no Snack-WP? Bootstrap, Foundation ou customizado?

**Comment by guilima** [comment]
Vamos lá.

Um [sistema de grid não é complexo](https://www.sitepoint.com/understanding-css-grid-systems/) de montar. Já existem [vários exemplos](http://www.cssauthor.com/grid-systems/) por esse mundão, ainda mais com [display: flex~~box~~;](https://css-tricks.com/dont-overthink-flexbox-grids/) no jogo. Como podem ver acho que a nossa proposta aqui é pensar além do desenvolvimento/manutenção, pois já existem um leque de opções e a própria customização não possui um nível de complexidade tão grande como era imaginado. Portanto, acredito que o sistema de grid a ser escolhido deva ser um facilitador e flexível para todos.

Apenas para alinhar antes de colocar minha opinião: O sistema de grid serve para resolver problemas de posicionamento de elementos de composição "box" de forma "fluída" (%), então tudo que for uma peça estática ([media object](http://v4-alpha.getbootstrap.com/layout/media-object/)) ou possuir composição [mozaica](http://masonry.desandro.com/) ou coisa do genero não confere no escopo de um sistema de grid.

Para não ficar um discurso vazio vou me posicionar pontuando sobre o que um sistema de grid deveria ter como requisitos para aderirmos:
- Utilizar mixins para customização via CSS, [evitando a guerra semântica com o HTML](https://www.sitepoint.com/sass-semantically-extend-bootstrap/), contudo podemos manter [ambas](http://v4-alpha.getbootstrap.com/layout/grid/#mixins) as [opções](http://v4-alpha.getbootstrap.com/layout/grid/#predefined-classes), afinal teriamos flexibilidade para prototipação ou até alterações rápidas com classes no HTML.
- Possuir mais níveis de grid ([grid tiers](http://v4-alpha.getbootstrap.com/layout/overview/#responsive-breakpoints))
- [Tipografia responsiva](http://webdesign.tutsplus.com/tutorials/comprehensive-guide-when-to-use-em-vs-rem--cms-23984) dentro do possível (ñ compativel com IE 8)
- Ser compativel com o ie 8 **(?)**

Podemos snackzar o grid do bootstrap e colocar todos esses pontos em prática, mas gostaria de discutir mais a ideia com todos se seria esse o caminho.

**Comment by raphaelfabeni** [comment]
Ótimos pontos levantados @guilima ! 
Acredito que o grid tenha que ser exatamente isso. Simples e de fácil aplicação e que possa servir tanto pra protótipos (no caso usando as velhas amigas classes `.col2` e etc) ou para o projeto em si, sendo assim o grid customizado com `mixins`.
Eu particularmente esqueceria o IE8.

Um outro ponto a se pensar sobre grid é em relação à adoção ou não de _mobile-first_ e a questão da tipografia, eu não sei se o grid que trataria isso.

**Comment by adriano** [comment]
@raphaelfabeni a questão da tipografia é super importante e vamos levar em conta nessa nova versão (#1). Você acha que a tipografia pode ser tratada em uma issue isolada ou não tem como separá-la do grid?

**Comment by raphaelfabeni** [comment]
Acho que é algo pra colocar em prática e ir testando como funcionaria na prática. Juntando ambos, em tese, o arquivo de grid controlaria o comportamento da tipografia, que também teria suas declarações dentro do arquivo de tipografia, o que poderia causar um pouco de confusão. Acho que colocando a mão na massa, conseguimos ver qual se encaixa melhor.

**Comment by guilima** [comment]
Ainda não tinha pesquisado afundo sobre a tipografia em relação ao sistema de grid. Acho que me equivoquei, porque esse parece ser um assunto desacoplado do grid, no entanto dependendo de como for proposto pode possuir pequenas integrações com o grid, por exemplo um tamanho de fonte menor em colunas menores.

Como essa parte da "tipografia responsiva" envolve outras amarrações ([ritmo vertical](http://webdesign.tutsplus.com/articles/improving-layout-with-vertical-rhythm--webdesign-14070) e [unidades relativas](http://zellwk.com/blog/rem-vs-em/)) poderiamos discuti-las fora dessa issue. Partindo como base o que está proposto no [SassLine](https://sassline.com/) com resalvas ao uso da unidade _rem_ devido sua compatibilidade no IE.

**Comment by guilima** [comment]
Dando continuidade aos estudos a proposta é desenvolver e aplicar um sistema de grid com "display: inline-block" e "floats" (why not both?). A titulo de curiosidade apresento a diferença entre ambos:

inline-block
+controle do vertical-align;
+alinhamento centralizado com text-align: center;
-elemento pai deve possuir propriedade font-size com valor 0;
-devido ao item acima o escopo do controle da unidade 'em' fica limitado;

floats
-sem controle do vertical-align;
-necessário acrescentar pseudo elemento com a propriedade clear;

A base desse sistema será o bootstrap v4 porque já possui a estrutura optativa pronta entre mixins, e classes mais os níveis de breakpoints, apenas será necessário desenvolver uma parte para que por meio de uma variável possa trocar o sistema entre float ou inline-block. Assim o sistema fica opcional em sua totalidade e atinge o objetivo que é tornar o uso facilitado e flexivel à todos colaboradores num projeto. O ponto positivo do novo bootstrap é que foi desenvolvido com base no sass e também possui condicionais que removem css caso esteja desativado o uso de classes ou o modo flex.

Bibliografia:
https://www.codehive.io/boards/WgrpZOk
https://mixitup.kunkalabs.com/learn/tutorial/responsive-grids/
http://v4-alpha.getbootstrap.com/layout/grid/
https://chriswrightdesign.com/experiments/using-flexbox-today/
https://github.com/philipwalton/flexbugs

**Comment by guilima** [comment]
Removi o grid antigo e gerei um baseado no grid do bootstrap v4. Por opção irei manter ativo as classes do grid como `.col-*`, inclusive em produção. Motivo: imagino que a troca da semântica pela agilidade compense a todos da equipe.
