### ISSUE TITLE
Plugin para backup de um site em Worpdress

### ISSUE THREAD

**Issue by adriano** [snack/snack-wp#4]
Sempre usei o [WP-DB-Backup](https://wordpress.org/plugins/wp-db-backup/).

Vantagens:
- Permite criar uma rotina automática de backup (Diário, Semanal ou Mensal)
- O backup é enviado por email
- Plugin mais popular de backup do Wordpress (400,000+ instalados)

Desvantagem:
- Só faz backup do banco de dados, não dos arquivos (pasta do tema e uploads)

Alguém usa ou recomenda outro plugin?

**Comment by sansegato** [comment]
@adriano nos últimos projetos eu testei o [WP Database Backup ](https://wordpress.org/plugins/wp-database-backup/) que além do nome muito parecido, funciona praticamente da mesma maneira que o outro. Como esse tinha atualizações mais constantes, achei que valia o teste. Mas não notei vantagens em relação ao WP-DB-Backup.

**Comment by adriano** [comment]
@sansegato esse plugin parece ter mais funcionalidades: além de fazer o backup, ele também restaura e pode armazenar os arquivos no Dropbox, FTP, Email ou Google drive.
