### ISSUE TITLE
Plugin para instalar o Google Analytics

### ISSUE THREAD

**Issue by adriano** [snack/snack-wp#6]
Aqui talvez o primeiro tipo de plugin da nossa lista que não seja uma unanimidade, alguns dizem que nem precisa de plugin para isso.

Vou começar sugerindo o [Google Analytics by MonsterInsights](https://wordpress.org/plugins/google-analytics-for-wordpress/). É o [mais popular do Wordpress](https://wordpress.org/plugins/browse/popular/) e possui as seguintes funcionalidades:
- Simple installation through integration with Google Analytics API: authenticate, select the site you want to track and you're done.
- Gives you incredibly nice visitor metric dashboards right in your WordPress install.
- Option to enable demographics and interest reports.
- Outbound link & downloads tracking.
- Configurable options to track outbound links either as pageviews or as events.
- Option to track just downloads as pageviews or events in Google Analytics.
- Option to track internal links with a particular format as outbound links, very useful for affiliate links that start with /out/, for instance.
- Possibility to ignore any user level and up, so all editors and higher for instance.
- Option to anonymize IP's for use in countries with stricter privacy regulations.
- Tracking of your search result pages and 404 pages.
- Full debug mode, including Firebug lite and ga_debug.js for debugging Google Analytics issues.

**Comment by ghost** [comment]
Esse é novo pra mim! Nunca tinha visto esse tipo de plugin :O 

O que me causa dúvida é sobre a questão de praticidade. Encaixando em nossos processos e tipo de clientes, quando não é redesign, nós que geralmente criamos uma conta de e-mail e a conta do Analytics, além de ter controle do código para inserir o Tracking Code e demais funcionalidades. 

Acho que um plugin seria útil para um heavy user de GA, que quer ter controle mais rápido de funcionalidades básicas, tipo um Ecommerce, talvez. Será que é realmente necessário termos um desses? (Só dúvida mesmo :P)

**Comment by adriano** [comment]
@Viapoli esse plugin mudou de nome, antes chamava Google Analytics for Wordpress.

Existem algumas métricas que vão além de inserir o código básico que já não são usadas somente por heavy users de GA. Muitos clientes ainda não tem essa maturidade, mas outros sim, com o pessoal do e-commerce que vc citou, por exemplo.

As funcionalidade que mais gosto nesse plugin:
- Registro automático de cliques para links externos (outbound link) e downloads de arquivos
- Possibilidade de não contar acesso de administradores (usuários logados)
- Possibilidade de registrar eventos (clique em botões de compartilhamento, vídeos e envio de formulários)
