### ISSUE TITLE
Galeria de fotos

### ISSUE THREAD

**Issue by adriano** [snack/snack-wp#8]
Como trabalhamos com galeria de fotos atualmente? Usamos as galerias nativas do Wordpress ou plugins? Quais as vantagens e desvantagens de cada abordagem?

**Comment by raphaelfabeni** [comment]
Até onde me lembre, uma alternativa para evitar o comportamento padrão das galerias era alterar o padrão de código das galeria do WP por uma customizada. Uma das melhores que utilizávamos era a lib [Flexslider](http://flexslider.woothemes.com/).

**Comment by hussani** [comment]
Acho mais viável definir um guideline para galerias pelo Snack, e depois ver como isto se adequa no Wordpress.

Tentar definir isto sem ter a definição de galerias pelo Snack parece ser uma inversão de responsabilidades entre os projetos.

No entanto, creio que galerias nativas ou com o comportamento modificado como o @raphaelfabeni citou são as melhores alternativas.

**Comment by guilima** [comment]
Exatamente @raphaelfabeni . Utilizamos a galeria nativa do wordpress alterando a função do shortcode para que se adapte ao flexslider, mas dependendo do projeto alteramos essa função. Por exemplo: [galeria integrada com o fancybox ou similares para visualização em modals](http://atlanticenergias.com.br/parques-eolicos/#gallery-2).

Um plugin para galeria só seria necessário em casos mais complexos do que a habitual integração que fazemos com o flexslider ou fancybox. Podemos estudar os plugins de galerias de fotos para verificar como estão implementando certas funcionalidades adicionais.
